# Site settings
title: Pillforge Project website
email: addisu.z.taddese@vanderbilt.edu
meta:
    description:
    author: Addisu Taddese

url: "http://pillforge.github.io" # the base hostname & protocol for your site
github_username:  pillforge

# Build settings
markdown: redcarpet
highlighter: pygments
encoding: UTF-8

# Exclude the following files/directories from being converted
exclude: ['.gitignore', 'CHANGELOG.md', 'Gemfile', 'Gemfile.lock', 'LICENSE.md', 'README.md', 'Rakefile']

#########################
# Plugin: jekyll-assets #
#########################

redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]

# Assets Pipeline
assets:
  sources:
    - _assets
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/bibliography
    - _assets/fonts

  # Minify and Compress Assets
  compress:
    css: sass
    js: uglifier

  # Disable asset gzip
  gzip: false

# Bibliography
scholar:
    style: _assets/bibliography/ieee.csl
    locale: en

    sort_by: year, month
    order: descending

    source: ./_bibliography
    bibliography: references.bib
    bibliography_template: bib

